#!/bin/bash -f

### --- Default Variables --- ###
source /home/savitb/bin/functions

METER_NAME='cpu_util'
STATISTIC_VAL='avg'
COMPARISON_OPERATOR='gt'
THRESHOLD_VAL=20
PERIOD_VAL=60
EVALUATION_PERIODS=1

USER="$(whoami)"
HOST_VM1="$USER"-mon-vm1

RESOURCE_ID=`nova list | grep $HOST_VM1 | awk '{print $2}'`


echo -n "Please enter a name for the alarm and press [ENTER]: "
read name

echo -n "Please enter your email address and press [ENTER]: "
read email

ALARM_ACTION="email://"$email

green_desc_title "Creating Alarm"
command_desc "ceilometer alarm-threshold-create --name $name --meter-name $METER_NAME --query resource_id=$RESOURCE_ID --description \"Alarm Configuration\" --statistic $STATISTIC_VAL --comparison-operator $COMPARISON_OPERATOR --threshold $THRESHOLD_VAL --period $PERIOD_VAL --evaluation-periods $EVALUATION_PERIODS --alarm-action $ALARM_ACTION"
ceilometer alarm-threshold-create --name $name --meter-name $METER_NAME --query resource_id=$RESOURCE_ID --description "Alarm Configuration" --statistic $STATISTIC_VAL --comparison-operator $COMPARISON_OPERATOR --threshold $THRESHOLD_VAL --period $PERIOD_VAL --evaluation-periods $EVALUATION_PERIODS --alarm-action $ALARM_ACTION
