#!/bin/bash
#   Four arguments
#   1. flavor name
#   2. image name
#   3. key name
#   4. security group name
#   5. vm name
unset ERR
if [[ -n "$1" ]]; then
   FLAVOR=$1
else
   ERR=1
fi
if [[ -n "$2" ]]; then
   IMAGE=$2
else
   ERR=1
fi
if [[ -n "$3" ]]; then
   KEY=$3
else
   ERR=1
fi
if [[ -n "$4" ]]; then
   SECURITY=$4
else
   ERR=1
fi
if [[ -n "$5" ]]; then
   VM_NAME=$5
else
   ERR=1
fi
if [[ -z "$ERR" ]]; then
    netid=`quantum net-list | grep $OS_TENANT_NAME-net | awk '{print $2}'`
    echo nova boot --flavor $FLAVOR --image $IMAGE --key_name $KEY --security_groups $SECURITY --nic net-id=$netid $VM_NAME
    nova boot --flavor $FLAVOR --image $IMAGE --key_name $KEY --security_groups $SECURITY --nic net-id=$netid $VM_NAME
    nova list
else
    echo "savi-run-server <flavor> <image> <key> <security group> <vm name>"
fi
