#!/bin/bash -f
source /home/savitb/bin/functions
USER=$(whoami)
KEY_NAME="$USER"key
SECGROUP_NAME=$USER
PROJECT_NAME=$OS_TENANT_NAME
VM="$USER"-vm1
MAIN_NETWORK="$PROJECT_NAME"-net
blue_desc_title "  Creating a $VM for ($USER)"
green_desc_title "Creating a $VM in $MAIN_NETWORK"

command_desc "quantum net-list"
NET_ID_MAIN=`quantum net-list -c id -c name | grep $MAIN_NETWORK | awk '{print $2}'`
echo "NET_ID_MAIN=$NET_ID_MAIN"

command_desc "nova boot --file /home/ubuntu/id_rsa=$HOME/.ssh/id_rsa --flavor m1.small --image Ubuntu64.2.1 --key_name $KEY_NAME --security_groups $SECGROUP_NAME --nic net-id=$NET_ID_MAIN $VM"
nova boot --file /home/ubuntu/id_rsa=$HOME/.ssh/id_rsa --file /etc/rc.local=$HOME/rc.local.vm1 --flavor m1.small --image Ubuntu64.2.1 --key_name $KEY_NAME --security_groups $SECGROUP_NAME --nic net-id=$NET_ID_MAIN $VM
yellow_desc "nova list"
nova list
