#!/bin/bash
unset ERR
if [[ -n "$1" ]]; then
   FLAVOR=$1
else
   ERR=1
fi
if [[ -n "$2" ]]; then
   IMAGE=$2
else
   ERR=1
fi
if [[ -n "$3" ]]; then
   KEY=$3
else
   ERR=1
fi
if [[ -n "$4" ]]; then
   SECURITY=$4
else
   ERR=1
fi
if [[ -n "$6" ]]; then
   HOST=$6
else
   ERR=1
fi
if [[ -n "$6" ]]; then
   NODE=$6
else
   ERR=1
fi
if [[ -n "$7" ]]; then
   VM_NAME=$7
else
   ERR=1
fi

if [[ -z "$ERR" ]]; then
    nova boot --flavor $FLAVOR --image $IMAGE --key_name $KEY --security_groups $SECURITY --hint force_hosts=$HOST --hint node_ids=$NODE $VM_NAME
    nova list
else
    echo "savi-run-server-host-node <flavor> <image> <key> <security group> <host> <node> <vm name>"
fi
